name: Build & Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      # Setup dotnet
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      # Tool Restore
      - name: Tool Restore
        run: dotnet tool restore
        working-directory: ./
      
      # Build
      - name: Build
        run: dotnet build --configuration Release
        working-directory: ./
      
      # Test
      - name: Run unit tests
        run: dotnet test --configuration Release
        working-directory: ./
