name: Publish Haya Attributes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore src/Haya/Haya.fsproj
      - name: Build
        run: dotnet build src/Haya/Haya.fsproj --configuration Release --no-restore
      - name: Run unit tests
        run: dotnet test --configuration Release
        working-directory: ./ 
      - name: Pack
        run: dotnet pack src/Haya/Haya.fsproj --configuration Release --no-build --output ./nupkg
      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
